services:
  - type: web
    name: WhatsApp Chat Replayer
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /static/index.html
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
